name: PrimeCore
author: PrimeAPI
version: 1.0.0
main: de.primeapi.primeplugins.spigotapi.PrimeCore
softdepend:
  - PlaceholderAPI
  - CloudNet-Bridge
  - CloudNetAPI
commands:
  coins:
  primecore:
    aliases:
      - spigotapi
load: STARTUP
loadbefore:
  - PrimePermissionsSystem
  - LobbySystem
  - MLGRush