name: PrimeCore
author: PrimeAPI
version: ${project.version}
main: de.primeapi.primeplugins.spigotapi.PrimeCore
softdepend:
  - PlaceholderAPI
  - CloudNet-Bridge
  - CloudNetAPI
  - Vault
commands:
  coins:
  afk:
  primecore:
    aliases:
      - spigotapi
load: STARTUP
loadbefore:
  - PrimePermissionsSystem
  - LobbySystem
  - MLGRush